version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" 

  app:
    build: .
    ports:
      - "3004:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/mydb"
    depends_on:
      - db
